FILE_PATH = "data/data.csv"

# Input data from task
TOWER_TYPE = "Sudok"
RELIABILITY_LEVEL = 2
TERRAIN_CATEGORY = 2
WIND_AREA = 1 # defines WIND_V_SPEC
TERRAIN_TYPE = 2 # defines Z_0 and K_R
FROST_AREA = "I2" # defines FROST_K1 and FROST_K2
FROST_TYPE = "WET SNOW"
MAX_OUTSIDE_TEMP = 33  # C DEGREES
MAX_CABLE_TEMP = 80 # C DEGREES
MIN_WIND_SPEED = 0.4 # m/s
SUN_POWER_OUTPUT = 1097 # W/m
K_ABSORPTION = 0.5
K_EMISSIVITY  = 0.5
SEA_HEIGHT = 400 # m
MIN_AMPACITY = 2000 # A
ISOLATOR_LENGTH = 5
MIN_HEIGHT_OVER_TERRAIN = 12 # m

Z_0 = 0.05
K_R = 0.189

FROST_K1 = 17.53
FROST_K2 = 0.070



C_DIR = 1
C_0 = 1
K_LC = 1
P_AIR = 1.25 # kg/m3
R = 0
K_P = 0.156

